# Nixpacks configuration for FastAPI backend in Railway
[variables]
    PYTHONDONTWRITEBYTECODE = "1"
    PYTHONUNBUFFERED = "1"
    
[phases.install]
    cmds = [
        "pip install --upgrade pip",
        "pip install -r requirements.txt"
    ]

[phases.build]
    cmds = [
        "python -c 'from app.database import engine; from app.models import indicador; indicador.Base.metadata.create_all(bind=engine); print(\"Database tables created successfully\")'",
    ]

[phases.start]
    cmd = "gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --host 0.0.0.0 --port $PORT" 